Models/ButtonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OOP_Ships_Project.Models
{
    public class DataModel
    {
        public int State { get; set; }

        public DataModel(int state)
        {
            State = state;
        }

    }
}

Controllers/ButtonController.cs
using OOP_Ships_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OOP_Ships_Project.Controllers
{
    public class ButtonController : Controller
    {
        // GET: Button
       static List<DataModel> data = new List<DataModel>(); // List of button states, ship alive count and player turn
       static List<DataModel> shipLocation = new List<DataModel>(); // List of generated ship locations, 1 represents ship, 2 represents empty water
        bool pageLoaded = false;

    // GET: Button
    public ActionResult Index()
        {
            if (!pageLoaded)
                SetShipPosition();
            return View("Index", data);
        }
        public ActionResult HandleButtonClick(string pButtons)
        {
            int buttonNumber = Int32.Parse(pButtons);
            if (((buttonNumber < 100 && data[202].State == 0) || (buttonNumber > 99 && data[202].State == 1)) && (data[buttonNumber].State != shipLocation[buttonNumber].State)) //Let the player who's turn it is, play
            {
                if (data[203].State == 0) data[203].State = 1; //Set a game in progress state
                
                if (data[202].State == 0) data[202].State = 1;
                else data[202].State = 0;
                data[buttonNumber].State = shipLocation[buttonNumber].State;

                if (shipLocation[buttonNumber].State == 1)
                {
                    if (buttonNumber < 100)
                        data[200].State--;
                    else
                        data[201].State--;
                }
            }
            return View("Index", data);
        }
        public ActionResult HandleTextInput(string AXcord, string AYcord, string BXcord, string BYcord)
        {
            int cord;
            if (data[202].State == 0 && (AXcord != "" || AYcord != ""))
            {
                cord = (Convert.ToInt32(AYcord) - 1) * 10 + (int)Convert.ToChar(AXcord) - 'a';
                data[cord].State = shipLocation[cord].State;
            }
            else if (data[202].State == 1 && (BXcord != "" || BYcord != ""))
            {
                cord = (Convert.ToInt32(BYcord) - 1) * 10 + (int)Convert.ToChar(BXcord) - 'a';
                data[cord + 100].State = shipLocation[cord + 100].State;
            }
            else { return View("Index", data); }

            if (data[202].State == 0) data[202].State = 1;
            else data[202].State = 0;
            return View("Index", data);
        }
        private void SetShipPosition()
        {
            pageLoaded = true;
            int[] alive = new int[2];
            const int maxShipCount = 10;

            for (int i = 0; i < 200; i++)
            {
                data.Add(new DataModel(0));
                shipLocation.Add(new DataModel(2));
            }
            
            Random random = new Random();
            for (int i = 0; i < maxShipCount * 2; i++)
            {
                if(i < 10)
                {
                    shipLocation[random.Next(100)].State = 1;
                    alive[0]++;
                }
                else
                {
                    shipLocation[random.Next(100) + 100].State = 1;
                    alive[1]++;
                }
            }
            data.Add(new DataModel(alive[0])); //Data index 200, status of Player A ships
            data.Add(new DataModel(alive[1])); //Data index 201, status of Player B ships
            data.Add(new DataModel(0)); //Data index 202, current players turn, convert bool to int
            data.Add(new DataModel(0)); // Data index 203, current game state
        }
    }
}

Views/Button/Index.cshtml
@model List<OOP_Ships_Project.Models.DataModel>


@{
    Layout = null;
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>

    <style type="text/css">
        .auto-style1 {
            position: absolute;
            top: 0px;
            left: 0px;
            height: 30px;
            width: 30px;
        }

        .btn {
            display: inline-flex;
            justify-content: center; /* center the content horizontally */
            align-items: center; /* center the content vertically */
            --padding-x: 1.2em;
        }
    </style>

</head>
<body>
    <h1 class="display-4" style="position: fixed; top: 50px; left: 420px;"><u>Project OOP Ships</u></h1>
    <h1 class="display-4" style="position: fixed; top: 100px; left: 140px;">Player A</h1>
    <h1 class="display-4" style="position: fixed; top: 100px; left: 840px;">Player B</h1>

    @using (Html.BeginForm("HandleButtonClick", "Button"))
    {
        //for (int i = 0; i < Model.Count; i++)
        //{
        //    if(Model[i].State) { Html.Raw('?'); }
        //    else { Html.Raw('0'); }
        //}
        @*@if (Model. == 1)
            {

            }*@
        <div id="div_Background" style="position: fixed; width: 1200px; height: 1000px; margin-right: 0px;">
            <h1 class="display-4" style="position: fixed; top: 50px; left: 420px;">Project OOP Ships</h1>
            <div id="div_X_Coords_Sector_A" style="width: 300px; height: 30px; position: inherit; top: 170px; left: 50px;">
                <table align="center" width="300" height="30">
                    <tr>
                        @for (int i = 0; i < 10; i++)
                        {
                            <td align="center" width="30">@Convert.ToChar(i + 'A')</td>
                        }
                    </tr>
                </table>
            </div>
            <div id="div_Y_Coords_Sector_A" style="width: 30px; height: 300px; position: inherit; top: 200px; left: 20px;">
                <table align="center" width="30" height="300">
                    @for (int i = 1; i < 11; i++)
                    {
                        <tr><td align="center">@i</td></tr>
                    }
                </table>
            </div>
            <div id="div_Player_A_Sector" style="width: 300px; height: 300px; position: inherit; top: 200px; left: 50px;">
                @*Player A area*@
                @for (int c = 0; c < 10; c++)
                {
                    for (int r = 0; r < 10; r++)
                    {
                        //id="@Convert.ToString("div_A_" + Convert.ToChar(c + 'A') + "_" + r)"
                        //value="ButtonAA_@(r + 1)"
                        <div style=" width: 30px; height: 30px; position: absolute; @Convert.ToString("top: " + r * 30 + "px"); @Convert.ToString("left: " + c * 30 + "px"); text-align: right;">
                            <Button class="btn" value=@(c+r*10) name="pButtons" type="submit" style="position: absolute; top: 0px; left: 0px; height: 30px; width: 30px; background-color: @((Model[c + r * 10].State == 1) ? "Red" : "turquoise");">
                                @if (Model[c + r * 10].State == 0)
                                {
                                    <p>?</p>
                                }
                                else if (Model[c + r * 10].State == 1)
                                {
                                    <img src="~/Images/destroyed_ship.png" width="25" height="25" />
                                }
                                else
                                {
                                    <p>0</p>
                                }
                            </Button>
                        </div>
                    }
                }
            </div>

            <div id="div_X_Coords_Sector_B" style="width: 300px; height: 30px; position: inherit; top: 170px; left: 750px;">
                <table align="center" width="300" height="30">
                    <tr>
                        @for (int i = 0; i < 10; i++)
                        {
                            <td align="center" width="30">@Convert.ToChar(i + 'A')</td>
                        }
                    </tr>
                </table>
            </div>
            <div id="div_Y_Coords_Sector_B" style="width: 30px; height: 300px; position: inherit; top: 200px; left: 720px;">
                <table align="center" width="30" height="300">
                    @for (int i = 1; i < 11; i++)
                    {
                        <tr><td align="center">@i</td></tr>
                    }
                </table>
            </div>
            <div id="div_Player_B_Sector" style="width: 300px; height: 300px; position: inherit; top: 200px; left: 750px;">
                @*Player B area*@
                @for (int c = 0; c < 10; c++)
                {
                    for (int r = 0; r < 10; r++)
                    {
                        //id="@Convert.ToString("div_B_" + Convert.ToChar(c + 'A') + "_" + r)"
                        <div style=" width: 30px; height: 30px; position: absolute; @Convert.ToString("top: " + r * 30 + "px"); @Convert.ToString("left: " + c * 30 + "px"); text-align: right;">
                            <Button class="btn" value=@(c+r*10+100) name="pButtons" type="submit" style="position: absolute; top: 0px; left: 0px; height: 30px; width: 30px; background-color: @((Model[c + r * 10 + 100].State == 1) ? "Red" : "turquoise");">
                                @if (Model[c + r * 10 + 100].State == 0)
                                {
                                    <p>?</p>
                                }
                                else if (Model[c + r * 10 + 100].State == 1)
                                {
                                    <img src="~/Images/destroyed_ship.png" width="25" height="25" />
                                }
                                else
                                {
                                    <p>0</p>
                                }
                            </Button>
                        </div>
                    }
                }


            </div>
        </div>
        if (Model[203].State == 0) // Mark starting player
        {
            <h1 class="display-4" style="position: fixed; top: 500px; left: 90px;">Player A starts!</h1>
        }
        if (Model[203].State == 1) // Mark who's turn it is
        {
            <h1 class="display-4" style="position: fixed; top: 500px; @Convert.ToString("left: " + (130 + Model[202].State*700) + "px");">Your turn!</h1>
        }
        <div style="position: fixed; top: 350px; left: 460px;">
            <h1>Ships Alive</h1>
            <h2 style="position: fixed; top: 400px; left: 505px;">A: @Model[200].State</h2>
            <h2 style="position: fixed; top: 430px; left: 505px;">B: @Model[201].State</h2>
        </div>
    }

    @using (Html.BeginForm("HandleTextInput", "Button"))
    {
        <div id="div_Attack_Sector_A" style="width: 200px; height: 300px; position: inherit; top: 200px; left: 400px;">

            <Label style="position: fixed; top: 180px; left: 425px; height: 20px; width: 100px">X Coordination</Label>
            <input type="text" name="AXcord" style="position: fixed; top: 200px; left: 425px; height: 20px; width: 100px" />

            <Label style="position: fixed; top: 230px; left: 425px; height: 20px; width: 100px">Y Coordination</Label>
            <input type="text" name="AYcord" style="position: fixed; top: 250px; left: 425px; height: 20px; width: 100px" />

            <Button type="submit" style="position: fixed; top: 300px; left: 450px; height: 35px; width: 50px">
                Fire!
            </Button>
        </div>
        <div id="div_Attack_Sector_B" style="width: 200px; height: 300px; position: inherit; top: 200px; left: 550px;">

            <Label style="position: fixed; top: 180px; left: 570px; height: 20px; width: 100px">X Coordination</Label>
            <input type="text" name="BXcord" style="position: fixed; top: 200px; left: 570px; height: 20px; width: 100px" />

            <Label style="position: fixed; top: 230px; left: 570px; height: 20px; width: 100px">Y Coordination</Label>
            <input type="text" name="BYcord" style="position: fixed; top: 250px; left: 570px; height: 20px; width: 100px" />

            <Button type="submit" style="position: fixed; top: 300px; left: 595px; height: 35px; width: 50px">
                Fire!
            </Button>
        </div>
    }

    @if (Model[200].State == 0)
    {
        Model[203].State = 2;
        <script>alert("Congratulations! Player A won! GGs <3");</script>
    }
    @if (Model[201].State == 0)
    {
        Model[203].State = 2;
        <script>alert("Congratulations! Player B won! GGs <3");</script>
    }

<footer>
    <p>Author: Matus Kozuch/Nikodem Pradka</p>
    <p><a href="https://github.com/xkzch01/OOP_Lode">GitHub</a></p>
</footer>
</body>
</html>